# Generated by Django 5.2 on 2025-05-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=300),
        ),
    ]
