version: "3.9"

services:
  web:
    build: .
    command: sh ./entrypoint.sh
    env_file:
      - .env.prod
    restart: always
    depends_on:
      - nginx
    expose:
      - "8000"
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - django_logs:/app/logs

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  static_data:
  media_data:
  django_logs:
