# version: "3.9"

services:
  web:
    build: .
    command: sh ./entrypoint.sh
    environment:
      - DJANGO_ENV=dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - .env.dev
