# Generated by Django 5.2 on 2025-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="author",
            field=models.CharField(default="Unknown", max_length=300),
        ),
    ]
