# Generated by Django 5.2 on 2025-05-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_quote_author"),
        ("users", "0005_remove_user_full_name_profile_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="poster",
        ),
        migrations.AddField(
            model_name="quote",
            name="user_profile",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
