# Generated by Django 5.2 on 2025-05-19 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_quote_author"),
        ("users", "0004_profile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.profile",
            ),
        ),
    ]
