# Generated by Django 5.2 on 2025-05-26 10:41

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_quoteauthor_alter_quote_author"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
