# Generated by Django 5.2 on 2025-05-26 12:13

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_quote_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteauthor",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
