# Generated by Django 5.2 on 2025-05-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_quoteauthor_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteauthor",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
