# Generated by Django 5.2 on 2025-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0008_alter_quoteauthor_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoteauthor",
            name="slug",
        ),
    ]
