# Generated by Django 5.2 on 2025-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0009_remove_quoteauthor_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteauthor",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
