# Generated by Django 5.2 on 2025-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0010_quoteauthor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteauthor",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
